package dev.hloth.zaragoza_tarjeta_bus

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

data class Candidate(val name: String, val scheme: ColorScheme)

val CANDIDATE_PALETTES = listOf(
    Candidate(
        "LightGreen",
        lightColorScheme(
            primary = Color(0xFF3A6A22), onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFB3E595), onPrimaryContainer = Color(0xFF102000),
            secondary = Color(0xFF516445), onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFD3E9C5), onSecondaryContainer = Color(0xFF102000),
            tertiary = Color(0xFF006A66), onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF73F7F0), onTertiaryContainer = Color(0xFF00201F),
            background = Color(0xFFF5FBF0), onBackground = Color(0xFF181D15),
            surface = Color(0xFFF5FBF0), onSurface = Color(0xFF181D15),
            surfaceVariant = Color(0xFFDBE6D4), onSurfaceVariant = Color(0xFF41493B),
            outline = Color(0xFF717A6A), outlineVariant = Color(0xFFBFCAB8),
        ),
    ),
    Candidate(
        "Beige",
        lightColorScheme(
            primary = Color(0xFF695E3A), onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFE8D9B0), onPrimaryContainer = Color(0xFF221B00),
            secondary = Color(0xFF645E4E), onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFEAE2CF), onSecondaryContainer = Color(0xFF201B0C),
            tertiary = Color(0xFF456550), onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFC7EBD2), onTertiaryContainer = Color(0xFF02210E),
            background = Color(0xFFFEF9EE), onBackground = Color(0xFF1E1B13),
            surface = Color(0xFFFEF9EE), onSurface = Color(0xFF1E1B13),
            surfaceVariant = Color(0xFFEAE2CF), onSurfaceVariant = Color(0xFF4C4637),
            outline = Color(0xFF7D7766), outlineVariant = Color(0xFFCDC6B4),
        ),
    ),
    Candidate(
        "Teal",
        lightColorScheme(
            primary = Color(0xFF29685F), onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF9BDBD0), onPrimaryContainer = Color(0xFF00201C),
            secondary = Color(0xFF4B635F), onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFCCE8E3), onSecondaryContainer = Color(0xFF081F1C),
            tertiary = Color(0xFF37647A), onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFC2E8FE), onTertiaryContainer = Color(0xFF001F2B),
            background = Color(0xFFECFDFA), onBackground = Color(0xFF121E1C),
            surface = Color(0xFFECFDFA), onSurface = Color(0xFF121E1C),
            surfaceVariant = Color(0xFFCDE8E3), onSurfaceVariant = Color(0xFF344B47),
            outline = Color(0xFF637C77), outlineVariant = Color(0xFFB1CCC7),
        ),
    ),
    Candidate(
        "SkyBlue",
        lightColorScheme(
            primary = Color(0xFF3A627E), onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFA8CFEF), onPrimaryContainer = Color(0xFF001E2F),
            secondary = Color(0xFF51606D), onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFD4E5F3), onSecondaryContainer = Color(0xFF0E1D27),
            tertiary = Color(0xFF695873), onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFEFDCFB), onTertiaryContainer = Color(0xFF24162D),
            background = Color(0xFFF5FAFF), onBackground = Color(0xFF141C23),
            surface = Color(0xFFF5FAFF), onSurface = Color(0xFF141C23),
            surfaceVariant = Color(0xFFD3E5F4), onSurfaceVariant = Color(0xFF394955),
            outline = Color(0xFF697987), outlineVariant = Color(0xFFB7C9D8),
        ),
    ),
    Candidate(
        "Lavender",
        lightColorScheme(
            primary = Color(0xFF625885), onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFC9BCEF), onPrimaryContainer = Color(0xFF1B163C),
            secondary = Color(0xFF615B70), onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFE6DFF7), onSecondaryContainer = Color(0xFF1D192A),
            tertiary = Color(0xFF834F5E), onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFED9E2), onTertiaryContainer = Color(0xFF370B1B),
            background = Color(0xFFFAF8FF), onBackground = Color(0xFF1C1A22),
            surface = Color(0xFFFAF8FF), onSurface = Color(0xFF1C1A22),
            surfaceVariant = Color(0xFFE5E0F3), onSurfaceVariant = Color(0xFF494554),
            outline = Color(0xFF797585), outlineVariant = Color(0xFFC9C4D6),
        ),
    ),
    Candidate(
        "Rose",
        lightColorScheme(
            primary = Color(0xFF825059), onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFF0B7C0), onPrimaryContainer = Color(0xFF360C18),
            secondary = Color(0xFF6F595C), onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF7DCE0), onSecondaryContainer = Color(0xFF29161A),
            tertiary = Color(0xFF735A42), onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFCDDC1), onTertiaryContainer = Color(0xFF2A1800),
            background = Color(0xFFFFF8F9), onBackground = Color(0xFF24191A),
            surface = Color(0xFFFFF8F9), onSurface = Color(0xFF24191A),
            surfaceVariant = Color(0xFFF7DCE0), onSurfaceVariant = Color(0xFF574145),
            outline = Color(0xFF897175), outlineVariant = Color(0xFFDAC0C4),
        ),
    ),
    Candidate(
        "Peach",
        lightColorScheme(
            primary = Color(0xFF7C5639), onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFF5C6A5), onPrimaryContainer = Color(0xFF2C1600),
            secondary = Color(0xFF6D5B4E), onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF5DECF), onSecondaryContainer = Color(0xFF27180C),
            tertiary = Color(0xFF56633F), onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFDAE8BE), onTertiaryContainer = Color(0xFF171E00),
            background = Color(0xFFFFF8F4), onBackground = Color(0xFF221A14),
            surface = Color(0xFFFFF8F4), onSurface = Color(0xFF221A14),
            surfaceVariant = Color(0xFFF3DFD2), onSurfaceVariant = Color(0xFF534439),
            outline = Color(0xFF857468), outlineVariant = Color(0xFFD6C3B6),
        ),
    ),
    Candidate(
        "Mint",
        lightColorScheme(
            primary = Color(0xFF31694C), onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFA9E5C3), onPrimaryContainer = Color(0xFF002110),
            secondary = Color(0xFF4D6356), onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFCEE9D9), onSecondaryContainer = Color(0xFF0B1F15),
            tertiary = Color(0xFF126875), onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFA5EEFD), onTertiaryContainer = Color(0xFF001F25),
            background = Color(0xFFF0FCF5), onBackground = Color(0xFF141E18),
            surface = Color(0xFFF0FCF5), onSurface = Color(0xFF141E18),
            surfaceVariant = Color(0xFFD2E7DB), onSurfaceVariant = Color(0xFF394B41),
            outline = Color(0xFF697B70), outlineVariant = Color(0xFFB7CBBF),
        ),
    ),
    Candidate(
        "Amber",
        lightColorScheme(
            primary = Color(0xFF725B26), onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFF2D398), onPrimaryContainer = Color(0xFF251A00),
            secondary = Color(0xFF695D46), onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF0E1C6), onSecondaryContainer = Color(0xFF241A00),
            tertiary = Color(0xFF3D6843), onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFBFEEC3), onTertiaryContainer = Color(0xFF002200),
            background = Color(0xFFFFF9EE), onBackground = Color(0xFF1F1B13),
            surface = Color(0xFFFFF9EE), onSurface = Color(0xFF1F1B13),
            surfaceVariant = Color(0xFFECE1CF), onSurfaceVariant = Color(0xFF4E4637),
            outline = Color(0xFF7F7666), outlineVariant = Color(0xFFD0C5B4),
        ),
    ),
    Candidate(
        "Slate",
        lightColorScheme(
            primary = Color(0xFF525E7D), onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFAAB6D9), onPrimaryContainer = Color(0xFF0A1B35),
            secondary = Color(0xFF5A5E6C), onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFDDE2F3), onSecondaryContainer = Color(0xFF171B27),
            tertiary = Color(0xFF735668), onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFFBD9EE), onTertiaryContainer = Color(0xFF2C1323),
            background = Color(0xFFF7F9FF), onBackground = Color(0xFF191B23),
            surface = Color(0xFFF7F9FF), onSurface = Color(0xFF191B23),
            surfaceVariant = Color(0xFFDCE2F5), onSurfaceVariant = Color(0xFF414656),
            outline = Color(0xFF717788), outlineVariant = Color(0xFFC1C6D9),
        ),
    ),
    Candidate(
        "Olive",
        lightColorScheme(
            primary = Color(0xFF57642D), onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFCBD79A), onPrimaryContainer = Color(0xFF1A1E00),
            secondary = Color(0xFF5C6149), onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFE1E5C9), onSecondaryContainer = Color(0xFF1A1D04),
            tertiary = Color(0xFF1C6A5A), onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFA6F1DE), onTertiaryContainer = Color(0xFF00211A),
            background = Color(0xFFF9FAEF), onBackground = Color(0xFF1B1C14),
            surface = Color(0xFFF9FAEF), onSurface = Color(0xFF1B1C14),
            surfaceVariant = Color(0xFFE1E4D1), onSurfaceVariant = Color(0xFF454839),
            outline = Color(0xFF767968), outlineVariant = Color(0xFFC5C8B6),
        ),
    ),
    Candidate(
        "Terracotta",
        lightColorScheme(
            primary = Color(0xFF82533C), onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFE0A98F), onPrimaryContainer = Color(0xFF311300),
            secondary = Color(0xFF705A4F), onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFF9DDD0), onSecondaryContainer = Color(0xFF29170D),
            tertiary = Color(0xFF5D613B), onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFE2E6B9), onTertiaryContainer = Color(0xFF1C1D00),
            background = Color(0xFFFFF8F5), onBackground = Color(0xFF231A15),
            surface = Color(0xFFFFF8F5), onSurface = Color(0xFF231A15),
            surfaceVariant = Color(0xFFF5DED4), onSurfaceVariant = Color(0xFF55433B),
            outline = Color(0xFF87736A), outlineVariant = Color(0xFFD8C2B8),
        ),
    ),
)
